on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
        
      - name: Install dependencies
        run: |
          install.packages(c("lintr"))
        shell: Rscript {0}

      - name: Lint
        run: lintr::lint_dir(path="Rcode")
        shell: Rscript {0}
